name: ZAP Baseline Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run ZAP Baseline Scan
        uses: owasp/zap-action@v0.8.2
        with:
          target: https://juice-shop.herokuapp.com/
