name: OWASP ZAP Scan

on:
    push: # Trigger the scan when code is pushed
        

jobs:
    zap_scan:
        runs-on: windows-latest
        name: Scan the web application
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                ref: master

            - name: Run ZAP Baseline Scan
              uses: zaproxy/action-baseline@v0.12.0
              with:
                target: 'https://juice-shop.herokuapp.com/#'
                token: ${{secrets.GITHUB_TOKEN }}
                docker_name:
                    'ghrc.io/zaproxy/zaproxy:stable'
                






            
