name: OWASP ZAP Scan

on:
    push:
        branches:
            - owaspzap

jobs:
    zap_scan:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run ZAP scan
              run: zap-cli --spider https://juice.shop.herokuapp.com/ && zap-cli --active scan http://juice-shop.herokuapp.com/
              




            
