 name: Cypress Tests Lesson 2
on:
push:
branches:
- main
jobs:
cypress:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2

-name: Install dependencies
run: npm ci

-name: Run Cypree tests
run: npx cypress run --config
baseURL=https://example.cypress.io --env
email=jasmine@email.com
